src/BowlingScore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BowlingScore.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

src/BowlingScore/Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BowlingScore.Models;

namespace BowlingScore.Controllers
{
    public class ScoreController : Controller
    {
        //
        // GET: /Score/
        internal static BowlingModel juego;
        public ActionResult Index()
        {
            inicilizaJuego();
            return View(juego);
        }

        private static void inicilizaJuego()
        {
            juego = new BowlingModel();
            juego.Jugador = 1;
            juego.Turno = 1;
            juego.Oportunidad = 1;
        }

        public ActionResult RegistraChuza()
        {
            juego.ActualizaScore(10);
            return View("Index",juego);
            
        }

        public ActionResult RegistraTiro()
        {
            string scoreNumber = Request.Form["txtPinos"];
            juego.ActualizaScore(int.Parse(scoreNumber));
            return View("Index",juego);            
        }
    }
}

src/BowlingScore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Bienvenido a no te hagas Bolas!!</h1>
@Html.ActionLink("Iniciar Nuevo Juego","Index","Score", null, new {@id="btnNuevo"})

src/BowlingScore/Views/Score/Index.cshtml
@model BowlingScore.Models.BowlingModel
@{
    ViewBag.Title = "Index";
}

<h2>Score del Juego</h2>
<span>Juego Iniciado</span>

<fieldset>
<span>Turno: Jugador 1</span><br />
<span>Frame: @Model.Turno</span><br /><span>Oportunidad: @Model.Oportunidad</span>
<table id="tblScore" border="1" cellpadding="2" width="400">
<thead>
<tr>
<th>Jugador</th>
@for (int i = 1; i <= 10; i++)
{
    if (Model.Turno==i){
        @Html.Raw("<th bgcolor='red'>" + @i + "</th>");
    }
    else{
        @Html.Raw("<th>" + @i + "</th>");
    }

}
<th>score</th>
</tr>
</thead>
<tbody>
<tr>
<td>Jugador 1</td>
@for (int i = 1; i <= 10; i++)
{
    <td>@Model.Score[0, i]</td>}
<td>@Model.Score[0, 12]</td>
</tr>
<tr>
<td>Jugador 2</td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td>0</td>
</tr>
<tr>
<td>Jugador 3</td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td>0</td>
</tr>
<tr>
<td>Jugador 4</td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td> - </td>
<td>0</td>
</tr>
</tbody>
</table>
@using (Html.BeginForm("RegistraTiro", "Score"))
{
    <span>Pinos tirados: @Html.TextBox("txtPinos")</span>    
    <input type="submit" id="btnOk" value="Ok" />       
    
    @Html.ActionLink("Chuza", "RegistraChuza", "Score", null, new { @id = "btnChuza" });
}
</fieldset>

src/BowlingScore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>